"""
Sellvance — Hub de Integrações
Gerencia conexões com todas as plataformas de anúncios, marketplaces e ferramentas
"""

INTEGRATIONS_CATALOG = {

    # ── MARKETPLACES ───────────────────────────────────────────────────────────
    'mercado_livre': {
        'name': 'Mercado Livre',
        'category': 'marketplace',
        'icon': '🛒',
        'color': '#ffe600',
        'text_color': '#1a1a00',
        'description': 'Sincronize pedidos, estoque, anúncios e métricas do ML em tempo real.',
        'features': ['Pedidos automáticos', 'Estoque sincronizado', 'Métricas de anúncio', 'Perguntas e respostas', 'Reputação da conta'],
        'auth_type': 'oauth2',
        'oauth_url': 'https://auth.mercadolibre.com.br/authorization',
        'docs_url': 'https://developers.mercadolivre.com.br',
        'difficulty': 'Fácil',
        'setup_time': '5 min',
        'required_fields': [],
        'optional_fields': [],
        'steps': [
            {'title': 'Clique em "Conectar"', 'desc': 'Você será redirecionado para o Mercado Livre'},
            {'title': 'Faça login na sua conta', 'desc': 'Use a conta de vendedor que deseja conectar'},
            {'title': 'Autorize o Sellvance', 'desc': 'Clique em "Permitir" para dar acesso aos seus dados'},
            {'title': 'Pronto!', 'desc': 'Seus dados serão sincronizados automaticamente a cada hora'},
        ],
    },

    'amazon': {
        'name': 'Amazon Seller',
        'category': 'marketplace',
        'icon': '📦',
        'color': '#ff9900',
        'text_color': '#1a0a00',
        'description': 'Conecte sua conta Amazon Seller Central para pedidos, FBA, anúncios Sponsored e Buy Box.',
        'features': ['Pedidos e FBA', 'Sponsored Products', 'Buy Box tracker', 'Reviews automáticos', 'Relatórios de vendas'],
        'auth_type': 'api_keys',
        'docs_url': 'https://developer-docs.amazon.com/sp-api',
        'difficulty': 'Médio',
        'setup_time': '10 min',
        'required_fields': [
            {'key': 'seller_id', 'label': 'Seller ID', 'placeholder': 'Ex: A1B2C3D4E5F6G7', 'type': 'text'},
            {'key': 'marketplace_id', 'label': 'Marketplace ID', 'placeholder': 'Ex: A2Q3Y263D00KWC (Brasil)', 'type': 'text'},
            {'key': 'client_id', 'label': 'LWA Client ID', 'placeholder': 'amzn1.application-oa2-client.xxx', 'type': 'text'},
            {'key': 'client_secret', 'label': 'LWA Client Secret', 'placeholder': '••••••••••••••••••••', 'type': 'password'},
            {'key': 'refresh_token', 'label': 'Refresh Token', 'placeholder': 'Atexxxxx', 'type': 'password'},
        ],
        'optional_fields': [],
        'steps': [
            {'title': 'Acesse Seller Central', 'desc': 'Vá em Apps & Services → Develop Apps'},
            {'title': 'Crie uma aplicação', 'desc': 'Clique em "Add new app client" e preencha os dados'},
            {'title': 'Gere as credenciais', 'desc': 'Copie o Client ID, Client Secret e gere o Refresh Token via SP-API'},
            {'title': 'Cole as credenciais aqui', 'desc': 'Preencha os campos ao lado e clique em Conectar'},
        ],
    },

    'tiktok_shop': {
        'name': 'TikTok Shop',
        'category': 'marketplace',
        'icon': '🎵',
        'color': '#ff0050',
        'text_color': '#fff',
        'description': 'Sincronize produtos, pedidos, afiliados e métricas de vídeo do TikTok Shop.',
        'features': ['Produtos e estoque', 'Pedidos em tempo real', 'Métricas de afiliados', 'Shop Ads', 'Live commerce'],
        'auth_type': 'oauth2',
        'oauth_url': 'https://auth.tiktok-shops.com/api/v2/token/get',
        'docs_url': 'https://partner.tiktokshop.com/docv2',
        'difficulty': 'Fácil',
        'setup_time': '5 min',
        'required_fields': [],
        'optional_fields': [],
        'steps': [
            {'title': 'Clique em "Conectar"', 'desc': 'Você será redirecionado ao TikTok Shop Seller Center'},
            {'title': 'Faça login', 'desc': 'Use sua conta de vendedor TikTok Shop'},
            {'title': 'Autorize o Sellvance', 'desc': 'Confirme as permissões de acesso'},
            {'title': 'Pronto!', 'desc': 'Pedidos e métricas sincronizados a cada 30 minutos'},
        ],
    },

    'shopee': {
        'name': 'Shopee',
        'category': 'marketplace',
        'icon': '🧡',
        'color': '#ee4d2d',
        'text_color': '#fff',
        'description': 'Integre sua loja Shopee para gerenciar pedidos, produtos e campanhas de voucher.',
        'features': ['Pedidos automáticos', 'Gestão de produtos', 'Vouchers e promoções', 'Métricas da loja', 'Chat automático'],
        'auth_type': 'api_keys',
        'docs_url': 'https://open.shopee.com',
        'difficulty': 'Médio',
        'setup_time': '10 min',
        'required_fields': [
            {'key': 'shop_id', 'label': 'Shop ID', 'placeholder': 'Ex: 123456789', 'type': 'text'},
            {'key': 'partner_id', 'label': 'Partner ID', 'placeholder': 'Ex: 987654', 'type': 'text'},
            {'key': 'partner_key', 'label': 'Partner Key', 'placeholder': '••••••••••••••••', 'type': 'password'},
        ],
        'optional_fields': [],
        'steps': [
            {'title': 'Acesse Shopee Open Platform', 'desc': 'Vá em open.shopee.com e crie uma conta de desenvolvedor'},
            {'title': 'Crie um app', 'desc': 'Preencha os dados do aplicativo e aguarde aprovação'},
            {'title': 'Obtenha as credenciais', 'desc': 'Copie o Partner ID e Partner Key do painel'},
            {'title': 'Cole aqui e conecte', 'desc': 'Preencha os campos e clique em Conectar'},
        ],
    },

    'magalu': {
        'name': 'Magalu',
        'category': 'marketplace',
        'icon': '💙',
        'color': '#0086ff',
        'text_color': '#fff',
        'description': 'Conecte sua loja no Magalu Marketplace para pedidos, anúncios e métricas.',
        'features': ['Pedidos automáticos', 'Catálogo de produtos', 'Anúncios patrocinados', 'Reputação do vendedor'],
        'auth_type': 'api_keys',
        'docs_url': 'https://developers.magalu.com',
        'difficulty': 'Médio',
        'setup_time': '15 min',
        'required_fields': [
            {'key': 'api_key', 'label': 'API Key', 'placeholder': '••••••••••••••••••••••••••••••••', 'type': 'password'},
            {'key': 'tenant_id', 'label': 'Tenant ID', 'placeholder': 'Ex: luizalabs-xxx', 'type': 'text'},
        ],
        'optional_fields': [],
        'steps': [
            {'title': 'Acesse o portal do parceiro', 'desc': 'Vá em seller.magalu.com e acesse sua conta'},
            {'title': 'Solicite acesso à API', 'desc': 'Em Configurações → Integrações → API'},
            {'title': 'Gere sua API Key', 'desc': 'Clique em "Gerar nova chave" e copie'},
            {'title': 'Cole aqui', 'desc': 'Preencha o campo e conecte'},
        ],
    },

    # ── ADS ────────────────────────────────────────────────────────────────────
    'meta_ads': {
        'name': 'Meta Ads',
        'category': 'ads',
        'icon': '📘',
        'color': '#1877f2',
        'text_color': '#fff',
        'description': 'Importe campanhas do Facebook e Instagram Ads para análise e otimização com IA.',
        'features': ['Campanhas e conjuntos', 'Criativos e copies', 'Públicos personalizados', 'Conversões e ROAS', 'Gerenciador de negócios'],
        'auth_type': 'oauth2',
        'oauth_url': 'https://www.facebook.com/v18.0/dialog/oauth',
        'docs_url': 'https://developers.facebook.com/docs/marketing-apis',
        'difficulty': 'Fácil',
        'setup_time': '3 min',
        'required_fields': [],
        'optional_fields': [
            {'key': 'ad_account_id', 'label': 'ID da Conta de Anúncios', 'placeholder': 'act_XXXXXXXXXX (opcional)', 'type': 'text'},
        ],
        'steps': [
            {'title': 'Clique em "Conectar com Facebook"', 'desc': 'Login via OAuth — sem precisar de token manual'},
            {'title': 'Selecione a conta de anúncios', 'desc': 'Escolha qual conta de anúncios conectar'},
            {'title': 'Confirme as permissões', 'desc': 'Permita acesso a campanhas, insights e criativos'},
            {'title': 'Dados sincronizados!', 'desc': 'Campanhas importadas automaticamente a cada 4 horas'},
        ],
    },

    'google_ads': {
        'name': 'Google Ads',
        'category': 'ads',
        'icon': '🔴',
        'color': '#ea4335',
        'text_color': '#fff',
        'description': 'Conecte Google Ads para Search, Shopping, PMax e Display com análise IA completa.',
        'features': ['Search e Shopping', 'Performance Max', 'Display e YouTube', 'Conversões GA4', 'Smart Bidding insights'],
        'auth_type': 'oauth2',
        'oauth_url': 'https://accounts.google.com/o/oauth2/auth',
        'docs_url': 'https://developers.google.com/google-ads/api/docs',
        'difficulty': 'Fácil',
        'setup_time': '5 min',
        'required_fields': [],
        'optional_fields': [
            {'key': 'customer_id', 'label': 'Customer ID', 'placeholder': 'Ex: 123-456-7890 (opcional)', 'type': 'text'},
            {'key': 'mcc_id', 'label': 'MCC ID (agências)', 'placeholder': 'Ex: 987-654-3210 (opcional)', 'type': 'text'},
        ],
        'steps': [
            {'title': 'Clique em "Conectar com Google"', 'desc': 'Login seguro via Google OAuth 2.0'},
            {'title': 'Selecione a conta', 'desc': 'Escolha a conta Google Ads ou MCC'},
            {'title': 'Autorize o acesso', 'desc': 'Permita leitura de campanhas e relatórios'},
            {'title': 'Sincronizado!', 'desc': 'Dados de todas as campanhas importados em minutos'},
        ],
    },

    'tiktok_ads': {
        'name': 'TikTok Ads',
        'category': 'ads',
        'icon': '🎯',
        'color': '#000000',
        'text_color': '#fff',
        'description': 'Conecte o TikTok Ads Manager para campanhas de vídeo, Shop Ads e spark ads.',
        'features': ['Campanhas de vídeo', 'Shop Ads', 'Spark Ads', 'Públicos personalizados', 'Pixel TikTok'],
        'auth_type': 'oauth2',
        'oauth_url': 'https://ads.tiktok.com/marketing_api/auth',
        'docs_url': 'https://ads.tiktok.com/marketing_api/docs',
        'difficulty': 'Fácil',
        'setup_time': '5 min',
        'required_fields': [],
        'optional_fields': [],
        'steps': [
            {'title': 'Clique em "Conectar"', 'desc': 'Redirecionamento seguro ao TikTok Ads'},
            {'title': 'Faça login no TikTok For Business', 'desc': 'Use a conta vinculada ao seu Ads Manager'},
            {'title': 'Selecione o Ads Manager', 'desc': 'Escolha a conta de anúncios a conectar'},
            {'title': 'Pronto!', 'desc': 'Campanhas e métricas sincronizadas automaticamente'},
        ],
    },

    # ── ANALYTICS & DADOS ──────────────────────────────────────────────────────
    'google_analytics': {
        'name': 'Google Analytics 4',
        'category': 'analytics',
        'icon': '📊',
        'color': '#e37400',
        'text_color': '#fff',
        'description': 'Importe eventos, conversões e funis do GA4 para cruzar com dados de anúncios.',
        'features': ['Eventos e conversões', 'Funis de compra', 'Audiências GA4', 'UTM tracking', 'LTV por canal'],
        'auth_type': 'oauth2',
        'oauth_url': 'https://accounts.google.com/o/oauth2/auth',
        'docs_url': 'https://developers.google.com/analytics/devguides/reporting/data/v1',
        'difficulty': 'Fácil',
        'setup_time': '3 min',
        'required_fields': [],
        'optional_fields': [
            {'key': 'property_id', 'label': 'GA4 Property ID', 'placeholder': 'Ex: 123456789', 'type': 'text'},
        ],
        'steps': [
            {'title': 'Conecte com Google', 'desc': 'OAuth com a conta que tem acesso ao GA4'},
            {'title': 'Selecione a property', 'desc': 'Escolha o GA4 property do seu e-commerce'},
            {'title': 'Configure eventos', 'desc': 'Mapeie purchase, add_to_cart e checkout'},
            {'title': 'Cruzamento automático', 'desc': 'GA4 + Ads = atribuição precisa por canal'},
        ],
    },

    # ── PAGAMENTOS & ERP ───────────────────────────────────────────────────────
    'tiny_erp': {
        'name': 'Tiny ERP',
        'category': 'erp',
        'icon': '🗂️',
        'color': '#00a651',
        'text_color': '#fff',
        'description': 'Sincronize pedidos, estoque e notas fiscais do Tiny ERP com o Sellvance.',
        'features': ['Pedidos automáticos', 'Estoque em tempo real', 'Notas fiscais', 'Relatórios financeiros', 'Multi-marketplace'],
        'auth_type': 'api_keys',
        'docs_url': 'https://www.tiny.com.br/ajuda/api',
        'difficulty': 'Fácil',
        'setup_time': '5 min',
        'required_fields': [
            {'key': 'api_token', 'label': 'Token de API', 'placeholder': 'Cole seu token do Tiny ERP aqui', 'type': 'password'},
        ],
        'optional_fields': [],
        'steps': [
            {'title': 'Acesse o Tiny ERP', 'desc': 'Vá em Configurações → Integrações → API'},
            {'title': 'Gere o token', 'desc': 'Clique em "Gerar novo token" e copie'},
            {'title': 'Cole aqui', 'desc': 'Cole o token no campo abaixo'},
            {'title': 'Conectar', 'desc': 'Pedidos e estoque sincronizados em tempo real'},
        ],
    },

    'bling': {
        'name': 'Bling ERP',
        'category': 'erp',
        'icon': '💼',
        'color': '#0066cc',
        'text_color': '#fff',
        'description': 'Integre o Bling para sincronizar pedidos, estoque, NF-e e financeiro.',
        'features': ['Pedidos e NF-e', 'Estoque multi-CD', 'Financeiro', 'Logística', 'Relatórios'],
        'auth_type': 'oauth2',
        'oauth_url': 'https://www.bling.com.br/OAuth2/Login',
        'docs_url': 'https://developer.bling.com.br',
        'difficulty': 'Fácil',
        'setup_time': '5 min',
        'required_fields': [],
        'optional_fields': [],
        'steps': [
            {'title': 'Clique em "Conectar com Bling"', 'desc': 'OAuth direto — sem token manual'},
            {'title': 'Faça login no Bling', 'desc': 'Use suas credenciais de acesso'},
            {'title': 'Autorize o Sellvance', 'desc': 'Permita acesso a pedidos e estoque'},
            {'title': 'Sincronizado!', 'desc': 'NF-e e pedidos importados automaticamente'},
        ],
    },

    # ── FRETE & LOGÍSTICA ──────────────────────────────────────────────────────
    'melhor_envio': {
        'name': 'Melhor Envio',
        'category': 'logistics',
        'icon': '🚚',
        'color': '#00b14f',
        'text_color': '#fff',
        'description': 'Calcule frete, imprima etiquetas e rastreie entregas diretamente no Sellvance.',
        'features': ['Cotação automática', 'Impressão de etiquetas', 'Rastreamento', 'Correios + transportadoras', 'Frete grátis inteligente'],
        'auth_type': 'api_keys',
        'docs_url': 'https://docs.melhorenvio.com.br',
        'difficulty': 'Fácil',
        'setup_time': '5 min',
        'required_fields': [
            {'key': 'api_token', 'label': 'Token de Acesso', 'placeholder': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9...', 'type': 'password'},
        ],
        'optional_fields': [],
        'steps': [
            {'title': 'Acesse melhorenvio.com.br', 'desc': 'Faça login na sua conta'},
            {'title': 'Vá em Configurações → Tokens', 'desc': 'Clique em "Gerar token de acesso"'},
            {'title': 'Copie o token', 'desc': 'Guarde em local seguro — não será exibido novamente'},
            {'title': 'Cole aqui e conecte', 'desc': 'Cotações e etiquetas integradas ao Sellvance'},
        ],
    },

    # ── CRM & COMUNICAÇÃO ──────────────────────────────────────────────────────
    'whatsapp_business': {
        'name': 'WhatsApp Business API',
        'category': 'crm',
        'icon': '💬',
        'color': '#25d366',
        'text_color': '#fff',
        'description': 'Envie mensagens em massa, automatize respostas e faça campanhas segmentadas por RFM.',
        'features': ['Disparos em massa', 'Templates aprovados', 'Automações', 'Chatbot IA', 'Métricas de entrega'],
        'auth_type': 'api_keys',
        'docs_url': 'https://developers.facebook.com/docs/whatsapp/cloud-api',
        'difficulty': 'Médio',
        'setup_time': '20 min',
        'required_fields': [
            {'key': 'phone_id', 'label': 'Phone Number ID', 'placeholder': 'Ex: 1234567890123456', 'type': 'text'},
            {'key': 'wa_token', 'label': 'Access Token (permanente)', 'placeholder': 'EAAxxxxxxxxxx...', 'type': 'password'},
            {'key': 'waba_id', 'label': 'WhatsApp Business Account ID', 'placeholder': 'Ex: 9876543210', 'type': 'text'},
        ],
        'optional_fields': [],
        'steps': [
            {'title': 'Crie um app no Meta for Developers', 'desc': 'Acesse developers.facebook.com → Criar app → Business'},
            {'title': 'Adicione o produto WhatsApp', 'desc': 'Em Adicionar produtos, clique em WhatsApp → Configurar'},
            {'title': 'Configure o número', 'desc': 'Adicione e verifique seu número de telefone empresarial'},
            {'title': 'Gere token permanente', 'desc': 'Em System Users → Gerar token com permissão whatsapp_business_messaging'},
        ],
    },

    'rdstation': {
        'name': 'RD Station',
        'category': 'crm',
        'icon': '📧',
        'color': '#3ab0e8',
        'text_color': '#fff',
        'description': 'Sincronize leads, segmentações e e-mail marketing com o CRM do Sellvance.',
        'features': ['Leads automáticos', 'Segmentações RFM', 'E-mail marketing', 'Automações', 'Lead scoring'],
        'auth_type': 'api_keys',
        'docs_url': 'https://developers.rdstation.com',
        'difficulty': 'Fácil',
        'setup_time': '5 min',
        'required_fields': [
            {'key': 'api_key', 'label': 'API Key do RD Station', 'placeholder': 'Cole sua chave de API aqui', 'type': 'password'},
        ],
        'optional_fields': [],
        'steps': [
            {'title': 'Acesse o RD Station Marketing', 'desc': 'Vá em Configurações → Integrações → API'},
            {'title': 'Copie a API Key', 'desc': 'Clique em "Exibir chave de API" e copie'},
            {'title': 'Cole aqui', 'desc': 'Preencha o campo e clique em Conectar'},
            {'title': 'Sincronizado!', 'desc': 'Leads e e-mails integrados ao CRM RFM'},
        ],
    },
}

CATEGORIES = {
    'marketplace': {'label': 'Marketplaces', 'icon': '🏪', 'color': '#6c63ff'},
    'ads':         {'label': 'Plataformas de Ads', 'icon': '🎯', 'color': '#f59e0b'},
    'analytics':   {'label': 'Analytics', 'icon': '📊', 'color': '#10b981'},
    'erp':         {'label': 'ERP & Gestão', 'icon': '🗂️', 'color': '#3b82f6'},
    'logistics':   {'label': 'Logística & Frete', 'icon': '🚚', 'color': '#00b14f'},
    'crm':         {'label': 'CRM & Comunicação', 'icon': '💬', 'color': '#ec4899'},
}
